### ISSUE TITLE
логическая схема БД 

### ISSUE THREAD

**Issue by Anton-15** [Anton-15/-#12]
![image](https://user-images.githubusercontent.com/54960012/70728863-35a7e080-1d13-11ea-9a95-32f81e458d88.png)

**Comment by wldmr-key** [comment]
куда графики делись?
что это за дублирование атрибутов у посетителей?

**Comment by Anton-15** [comment]
ой графики забыл добавить

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70731459-c4b6f780-1d17-11ea-97de-da22fa352492.png)
![image](https://user-images.githubusercontent.com/54960012/70731534-e617e380-1d17-11ea-8872-63328fc189da.png)

**Comment by Anton-15** [comment]
у меня видимо неправильно таблицы сделаны ?

**Comment by Anton-15** [comment]
мне надо чтоб в таблице события отражались проходы и сотрудников и посетителей, а потом по id смотреть посетитель это или сотрудник ?

**Comment by Anton-15** [comment]
убрать у посетителей атрибуты (дата время прихода и ухода )  и если это посетитель просто late не заполнять ?

**Comment by Anton-15** [comment]
и если посетитель уже был на предприятии то в таблицу посетители он уже не добавляется, а если не был то добавляем его к списку посетители ?

**Comment by Anton-15** [comment]
мне наверное надо сделать чтоб в таблице события отражались проходы и сотрудников и посетителей, а потом по id смотреть это сотрудник ли  и если это не сотрудник то значит посетитель  ?
убрать у посетителей атрибуты (дата время прихода и ухода ) и если это посетитель просто late  не заполнять ?
и если посетитель уже был на предприятии то в таблицу посетители он уже не добавляется, а если не был то добавляем его к списку посетители ?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70737099-d5209f80-1d22-11ea-8448-22b54ff32194.png)

тогда вот правильная логическая схема ?

**Comment by wldmr-key** [comment]
нет. Как ты связываешь события с посетителями? Чуть позже заметил, что у тебя вообще нет идентификаторов для связей (внешних ключей) - это как? 

У посетителей тоже должен быть id. Чтобы их отличать имеет смысл выбрать одно из решений:
1. Развести идентификаторы сотрудников и посетителей по разным множествам
2. ввести в событие отдельный логический атрибут (посетитель/сотрудник)
3. использовать какой-нибудь еще атрибут - например, late - true/false: сотрудник, null - посетитель
4. что-то еще

**Comment by Anton-15** [comment]
а нельзя в качестве связи посетителя и события использовать паспорт ?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70741721-fedec400-1d2c-11ea-9b57-bb2d30668e02.png)

**Comment by Anton-15** [comment]
больше похоже на правду ?

**Comment by Anton-15** [comment]
возник вопрос про сущность Рабочие графики , она у меня используется только для того чтобы добавлять время входа в программу , чтобы та могла проверить опоздал сотрудник или нет . как ёё связать с сотрудником ?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70742182-02bf1600-1d2e-11ea-9a36-9f08e9e57800.png)
![image](https://user-images.githubusercontent.com/54960012/70742209-0f436e80-1d2e-11ea-9671-47fe4589332a.png)
![image](https://user-images.githubusercontent.com/54960012/70742232-1d918a80-1d2e-11ea-9d16-99deef2b0241.png)
![image](https://user-images.githubusercontent.com/54960012/70742280-37cb6880-1d2e-11ea-9f83-16c76e284709.png)
![image](https://user-images.githubusercontent.com/54960012/70742406-84af3f00-1d2e-11ea-9fa8-b18264c24b42.png)

**Comment by wldmr-key** [comment]
Антон, ты напрочь забыл все про БД. Что такое внешние ключи?!

**Comment by Anton-15** [comment]
это то с помощью чего устанавливается логическая связь между сущностями

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70744826-99420600-1d33-11ea-93c5-267437936a82.png)

**Comment by Anton-15** [comment]
про то что  у каждого названия должности и у каждого названия отдела должен быть id я понял. 
остался вопрос можно ли через id сотрудника и через паспорт связаться с событием ? 
а главный вопрос остался что делать с графиком ?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70750511-9cdb8a00-1d3f-11ea-91a6-25ad63bac62e.png)
![image](https://user-images.githubusercontent.com/54960012/70750561-b1b81d80-1d3f-11ea-9352-869212d35a9e.png)
![image](https://user-images.githubusercontent.com/54960012/70750600-c09ed000-1d3f-11ea-8c11-e56f238502e3.png)

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70750789-28edb180-1d40-11ea-9e56-1a4c370271ac.png)

**Comment by Anton-15** [comment]
пока переделывал заодно всё сделал на английском языке

**Comment by wldmr-key** [comment]
очевидно, у тебя не хватает внешних ключей для связей: "работник-график","событие-работник" и/или "событие-посетитель"
если бы они у тебя были, то соединение "событие-сотрудник-график" легко давало бы тебе индикацию опоздания

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70752736-415fcb00-1d44-11ea-8b4f-5ab88ccdfead.png)

**Comment by wldmr-key** [comment]
отлично!
а что будет первичным ключом для событий?

**Comment by Anton-15** [comment]
можно же добавить eventsid атрибут ? он будет ключом

**Comment by Anton-15** [comment]
и записывать туда либо pasportid если это посетитель либо workerid если это сотрудник

**Comment by Anton-15** [comment]
имеет место быть такое ? или какое то другое решение есть этому ?

**Comment by wldmr-key** [comment]
если делать так, как ты говоришь, то у тебя не получится уникальности - каждый проходит через проходную много раз. Поэтому, первичный ключ - это - либо сочетание (комбинация id + дата + время), либо искусственный ключ
Кстати, почему у тебя дата и время хранятся в отдельных полях? Это не претензия - это просто вопрос

**Comment by Anton-15** [comment]
наверное я лучше сделаю искусственный ключ

**Comment by Anton-15** [comment]
мне показалось, что так нагляднее выглядит таблица.  логика такая , в жизни мы спрашиваем либо какое число либо сколько время , совместно это не спрашивается

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/70786253-443ada00-1d9d-11ea-95f4-422eded37b6b.png)

**Comment by wldmr-key** [comment]
ok
