### ISSUE TITLE
ТЗ доработанное

### ISSUE THREAD

**Issue by Anton-15** [Anton-15/-#2]
[курсовая Рязанцев.docx](https://github.com/Anton-15/-/files/3622817/default.docx)

**Comment by wldmr-key** [comment]
Давай, доделаем его до более приличного уровня

>2.1.	Назначение системы.
Система предназначена для автоматизации прохода сотрудников на предприятие

это не совсем правильно выражено. Автоматизируется не проход

>Целью создания системы является:
•	снижение рутинной работы охранникам

нет. Удобство охранников никого не волнует. Их фонд зарплаты - да...

> •	представление возможности начальству отслеживать приход сотрудников предприятия 

в лексиконе ТЗ нет слова "начальство". И я сомневаюсь, что оно сильно страдало от отсутствия возможности "отслеживать"

> •	увеличить скорость доступа к структурированной информации о опозданиях 

а до твоей системы что было со скоростью? И до каких величин ее планируется увеличить? и В чем измеряется скорость?

Тут стоит быть корректнее со словами и не забывать, что первичная цель почти любого предприятия - это деньги или выживание.

---

Дальше структура документа пошла перпендикулярно ГОСТу. На каких основаниях? Они должны быть достаточно вескими..

Характеристика объекта автоматизации должна описывать основные процессы и сущности системы (не называя их процессами и сущностями). ты, например, с легкостью пишешь в функциях "определяется опоздал сотрудник или нет". А как это определить? Как определяется сотрудник или не сотрудник? Опоздал или пришел вовремя? Или не должен был приходить вообще?

**Comment by Anton-15** [comment]
[курсовая Рязанцев.docx](https://github.com/Anton-15/-/files/3647615/default.docx)

**Comment by Anton-15** [comment]
посмотрите пожалуйста я старался исправить все недочеты, но где то они еще явно есть

**Comment by wldmr-key** [comment]
Все стало значительно лучше

Первая претензия - русский язык. Постарайся прочитать текст, согласовать падежи и исправить самые вопиющие перлы типа "экономия на прогулах". Жанр ТЗ - это не разговорный сленг.

Краткие сведения стали слишком краткими. Что такое опоздания, что такое прогулы, что такое идентификация - об этом ничего не сказано.  В частности, 

> "Сотрудником является человек, который принят на работу. У каждого сотрудника есть свой рабочий график."

это у тебя в требованиях к системе... Почему? Я без системы не было сотрудников и графиков?! Конечно, это характеристики объекта!

Требования:

1. К системе в целом - для тебя это то, что система должна эмулировать удаленную идентификацию пользователей. Возможно, быть сопряженной с какими-то внешними БД. И другие подобные требования общего характера

2. Функциональные требования. По возможности полный список всех функций, которые будет выполнять система

3. Требования по надежности. Тебе виднее

4. Требования по программной совместимости. Их, ведь есть у тебя - при чем тут стандартизация?

5. Требования к документированию. Ну, как вариант, оформление схем БД и прочих вещей, которые ты и так оформишь

6. Требования к техническим средствам. Есть? А в мероприятиях по вводу в эксплуатацию ты их упоминаешь...

**Comment by Anton-15** [comment]
[курсовая Рязанцев.docx](https://github.com/Anton-15/-/files/3677520/default.docx)

**Comment by Anton-15** [comment]
у меня много недопониманий в связи не имения представлений как это должно все быть , чтоб продолжить написание исследовательской части.
 что еще нужно дописать про объект автоматизации ? 
что нужно рассказать об аналогах и сколько их указать ?
 и про концептуальную схему . схема системы в целом или схема базы данных для системы . и какие объекты там надо отразить .

**Comment by wldmr-key** [comment]
ТЗ уже вполне нормальное, так что задачу можно закрывать

Умоляю тебя, не вали в трекере все тексты и вопросы в один документ - разбивай их по отдельным задача. Этим ты упростишь жизнь и себе и мне
