### ISSUE TITLE
Описание предметной области.

### ISSUE THREAD

**Issue by Anton-15** [Anton-15/-#4]
[Описание предметной области.docx](https://github.com/Anton-15/-/files/3678639/default.docx)

**Comment by wldmr-key** [comment]
посмотри на свою же концептуальную схему и найди атрибуты, ни разу не упомянутые у тебя в описании
Там у тебя есть стрелочка, которая обозначает внешнюю таблицу, которая берется из отдела кадров. Ты это знаешь, я это знаю. После чтения твоих текстов больше никто об этом не узнает
А графики бывают еще и гибкими. А еще бывают отпуска. А еще бывает анализ данных

Еще раз подумай о том, что и как будет делать приложение и добавь в описание предметной области все понятия, которые будут использоваться далее

**Comment by wldmr-key** [comment]
и старайся не уместить весь текст в один абзац

**Comment by Anton-15** [comment]
[Описание предметной области.docx](https://github.com/Anton-15/-/files/3730050/default.docx)
не понимаю как написать про гибкие графики и отпуска как обыграть их в моей  системе ? а что такое анализ данных что надо про него написать ?

**Comment by wldmr-key** [comment]
фиксируются ли опоздания и прогулы? Если да, то как получить эту информацию
Является ли прогулом невыход на работу в отпуск? Работнику полагается отпуск? Все ли работники трудятся с 9 до 18? Все ли работники отдыхают в субботу и воскресенье?

**Comment by Anton-15** [comment]
[Описание предметной области.docx](https://github.com/Anton-15/-/files/3753052/default.docx)

**Comment by wldmr-key** [comment]
все неплохо (за исключением русского языка). Осталось внести информацию о графиках в концептуальную схему. Правда, для этого в описании неплохо было бы уточнить, а что из себя представляет рабочий график

**Comment by Anton-15** [comment]
[Описание предметной области.docx](https://github.com/Anton-15/-/files/3794331/default.docx)

**Comment by wldmr-key** [comment]
все хорошо. Осталось пригладить русский язык (немного по сравнению с остальными новыми разделами) и воплотить то, что здесь написано в концептуальной схеме

**Comment by Anton-15** [comment]
[Opisanie_predmetnoy_oblasti.docx](https://github.com/Anton-15/-/files/3820896/Opisanie_predmetnoy_oblasti.docx)

**Comment by wldmr-key** [comment]
пойдет
