### ISSUE TITLE
Аналоги

### ISSUE THREAD

**Issue by Anton-15** [Anton-15/-#5]
[Аналоги.docx](https://github.com/Anton-15/-/files/3678644/default.docx)

**Comment by wldmr-key** [comment]
неплохо. А сравнить и дать свою оценку? Это же исследование! Или хотя бы чужие оценки найти, а не только агитки...

**Comment by Anton-15** [comment]
[Аналоги.docx](https://github.com/Anton-15/-/files/3730147/default.docx)

**Comment by wldmr-key** [comment]
в принципе, уже лучше. Я бы советовал убрать пафос из агиток. И прочитать менее комплиментарные точки зрения на СКУД - вот, например, вроде таких - https://www.security-bridge.com/forum/oborudovanie_i_po_po_bezopasnosti/systemy_kontrolya_dostupa/ (2 минуты в гугле)

**Comment by Anton-15** [comment]
[Аналоги.docx](https://github.com/Anton-15/-/files/3794203/default.docx)
добавил недостатки и постарался найти пафос и убрал что нашел

**Comment by wldmr-key** [comment]
Нормально по существу. Но
а) следует решить проблемы с русским языком (внимательно прочитай весь текст или попроси это сделать знакомых)
б) лучше сразу оформлять тексты в соответствие с ГОСТ (шрифты, поля, стили списков и т.д.)

**Comment by Anton-15** [comment]
[Analogi.docx](https://github.com/Anton-15/-/files/3820831/Analogi.docx)

**Comment by wldmr-key** [comment]
уже значительно лучше, но
«Подъезжая к сией станцыи и глядя на природу в окно, у меня слетела шляпа. И. Ярмонкин»
найди у себя такой же оборот!
Нужно еще работать над текстом (в свободное от всей остальной курсовой время!)
