### ISSUE TITLE
Концептуальная схема

### ISSUE THREAD

**Issue by Anton-15** [Anton-15/-#6]
[Концептуальная модель данных.docx](https://github.com/Anton-15/-/files/3678645/default.docx)
этого наверное слишком мало для моей системы ?

**Comment by wldmr-key** [comment]
ты прав - маловато
должности - это не справочник?
отделы - это не справочник?
рабочие графики из воздуха брать будешь?
мы, вроде, говорили, что проходная у тебя не одна...
что происходит, если человек забыл/потерял пропуск?
посетителей без id фиксировать будем?
вахтеры на проходной существуют? Как узнать, кто из них пропустил жулика?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/66844509-10972b80-ef77-11e9-8058-ea0702387e6b.png)
подумал над схемой вроде все добавил только не понимаю как связать посетителей и рабочие графики

**Comment by wldmr-key** [comment]
а, время ухода, не?
а, атрибута проходной не будет?
а какие атрибуты должны быть у графика? - может тогда станет ясно с чем его связывать?

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/67246579-80ba1b80-f467-11e9-9a9d-8296956c8588.png)

**Comment by wldmr-key** [comment]
ну, это пока не совсем концептуальная схема. У них есть определенные правила нотации ))
Но до этого поговорим по существу
Когда в разных сущностях появляются одинаковые атрибуты, это должно настораживать
Время прихода и ухода у сотрудников и посетителей - разве это разные времена?
Я бы предположил, что это означает одно и то же
Правда, у события логичен только один атрибут - время, а определить приход или уход можно задав другой атрибут - направление.
С другой стороны, и предложенный тобой вариант - в одной сущности (назовем ее , скажем, посещение) фиксировать и приход, и уход тоже может быть удобен с точки зрения дальнейщего применения. Так что, выбирай...

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/67960509-72a88f80-fc0b-11e9-958e-509383e7f83e.png)

**Comment by Anton-15** [comment]
не сотрудник а " сотрудники" . таблица сотрудники в моей системе имеет список всех сотрудников и берет эти данные из отдела кадров. как мне это отобразить на блок схеме

**Comment by wldmr-key** [comment]
Я думаю не только "Сотрудники", но и должности, и отделы. Если ты обратил, уж, на это внимание, то лучше унифицировать наименования. Тогда, уж, "События" и "Посетители".
Нарисуй пунктирную черту, отделяющую внешние таблицы от внутренних, если для тебя это важно. В противном случае, достаточно просто написать, что эти таблицы заполняются и поддерживаются не в твоей системе, а в отделе кадров и других подразделениях предприятия (графики, например)
Штука, которую ты нарисовал, меньше похожа на концептуальную схему, чем предыдущая: появились какие-то Id с ключиками )) и типы данных. Ну, скажи, зачем тебе ими пугать собеседника? Тем более, они не всегда правильные. Или нуждаются в пояснении. Почему, например, время прихода - datetime, а время ухода - целое число? 

Что такое номер у посетителя?

И, традиционно, про рабочие графики... Теперь, они у тебя индивидуальны для каждого сотрудника... И выражаются тем же datetime. Это как? У токаря Иванова стоит график 31.10.2019 8:00:00.000, а у токаря Петрова стоит график 31.10.2019 8:00:00.000. Я правильно понимаю твой замысел? ))

Я не зря предлагал на лекциях такой формат концептуальных схем: писать вместо атрибутов примеры сущностей - в ряде случаев это может быть значительно более наглядно

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/68316290-4472f600-00ca-11ea-8964-7fde3348f454.png)

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/68316517-a7648d00-00ca-11ea-8113-08b2c949e7bc.png)

**Comment by wldmr-key** [comment]
все уже почти хорошо
1) сотрудников я бы тоже отнес за пунктирную черту - это общезаводская кадровая база
2) нужна ли дата у графиков? в какой форме они задаются. Так
6.11.2019 8:00 - 17:00
6.11.2019 9:00 - 18:00
6.11.2019 7:30 -16:15
7.11.2019 ...
Если да, то ты прав. Если нет, то нужно что-то исправлять. Обязательна ли связь сотрудника (директора, например) с графиком? Наверное, нет. 

3) в концептуальной схеме не принято дублировать связи атрибутами. Понятно, что у сотрудника есть должность, если от сущности должность идет дуга к сущности сотрудник. Поэтому, атрибут должность писать не нужно - должность определяется связью. И так далее

**Comment by Anton-15** [comment]
по поводу 2го . с одной стороны дата не нужна, но тогда при составлении отчета по опоздавшим мне же надо за какой то отрезок времени его выводить, получается дата нужна . так ?

**Comment by Anton-15** [comment]
а как обозначить что связь директора с графиком не нужна ?

**Comment by wldmr-key** [comment]
> а как обозначить что связь директора с графиком не нужна ?
а как обозначается немодальная (необязательная) связь на ER-диаграммах?

по поводу графиков - я говорю - это твой выбор.
Попробую тебе помочь таким способом: представь что ты - директор завода. Выпусти приказ о времени работы всех работников. Условия: рабочие на некоторых участках трудятся в две смены, тебе желательно не устраивать толкучки на проходной.

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/68408420-5cb04700-0196-11ea-9708-5d80a74ad45c.png)

**Comment by wldmr-key** [comment]
все нормально за исключением нотации ER-диаграмм. Кроме того есть одни существенные грабли, с которыми ты столкнешься  при реализации системы. Они заложены в концептуальной схеме
Кстати в описании предметной области ты совершенно справедливо пишешь

> Данные об опоздании сотрудника фиксируются при прохождении им через проходную позже указанного в рабочем графике времени, происходит это посредством нахождения рабочего графика этого сотрудника и сравнения времени его прихода с тем, что указан в графике.

это намек...

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/69165061-05996300-0b02-11ea-97be-0edbcec7fbfa.png)

**Comment by wldmr-key** [comment]
ты дуги специально сливаешь вместе и стрелки наоборот рисуешь, чтобы добиться моего замечания? ))
с атрибутным составом, вроде, все нормально

**Comment by Anton-15** [comment]
![image](https://user-images.githubusercontent.com/54960012/69256530-a7848280-0bca-11ea-937b-c636ccf108cc.png)

**Comment by wldmr-key** [comment]
ну, да!!!
